### PR TITLE
PR

### PR DESCRIPTION
**Pull request by kate2513**
Start Comment     
Diff Regression projects: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/projects-to-test-on.properties
Diff Regression config: https://raw.githubusercontent.com/checkstyle/contribution/master/checkstyle-tester/my_check.xml

### CODE REVIEW

**Comment by kate2513** [comment]
123

**Comment by kate2513** [comment]
456

**Comment by kate2513** [comment]
111

**Comment by kate2513** [comment]
run

**Comment by kate2513** [comment]
run

**Comment by kate2513** [comment]
report

**Comment by jack1515** [comment]
report

**Comment by jack1515** [comment]
report

**Pull request closed without merging**
